const String baseUrl = 'http://touristenziel.herokuapp.com/api';
// const String baseUrl = 'http://7018-180-244-129-247.ngrok.io/api'; //local test
const double defaultMargin = 24;
const String keyToken = "key_token";
const String keyUsername = "key_username";
const String keyName = "key_name";
const String keyAddress = "key_address";
const String keyEmail = "key_email";
const String keyRole = "key_role";
const String keyId = "key_id";
const String keyPhonenumber = "key_phonenumber";
const String keyIdStory = "key_id_story";
const String keyIdVisit = "key_id_visit";
const String loginFailed = "Login Error!";
