const String baseUrl = 'http://touristenziel.herokuapp.com/api';
const double defaultMargin = 24;
const String keyToken = "key_token";
const String keyUsername = "key_username";
const String keyName = "key_name";
const String keyAddress = "key_address";
const String keyEmail = "key_email";
const String keyRole = "key_role";
const String loginFailed = "Login Error!";